my_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 
  
  left_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: left_wheel_joint
    pid: {p: 2.0, i: 0.1, d: 0.01}

  right_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: right_wheel_joint
    pid: {p: 2.0, i: 0.1, d: 0.01}